### ISSUE TITLE
Different plot for comparing models

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/human-eval-bia#140]
After some [online feedback](https://x.com/HerrGlucksfall/status/1845721698618036244), I conclude it might make sense to change the box-plot that summarizes model performance. Maybe a violin plot would be better suited?

**Comment by nscherf** [comment]
Sounds good. We could also go for a jittered point plot / stripplot as in https://seaborn.pydata.org/generated/seaborn.stripplot.html

**Comment by haesleinhuepf** [comment]
I [discussed this with git-bob](https://github.com/haesleinhuepf/git-bob-playground/pull/52), which also suggeste the stripplot but did't like it. It's hard to spot differences between the llms.

```
sns.stripplot(data=ordered_numerical_data, palette= "Set2", orient='h', jitter=True, alpha=0.3, size=3)
```
![image](https://github.com/user-attachments/assets/8a4fc5a5-f3e1-42d9-bb99-eafd2fcccfc7)


The violin plot with some fine configuration might make sense:

```
sns.violinplot(data=ordered_numerical_data, palette= "Set2", orient='h', cut=0, bw=0.2, inner=None)
```

![image](https://github.com/user-attachments/assets/673d024e-423b-4f66-8751-55f909d9c044)

**Comment by nscherf** [comment]
The stripplot would only look reasonable with continuous values, but our values are basically discrete (from 0 to 1.0 with 0.1 steps). So this doesn't make sense. Sorry for not seeing this earlier.

**Comment by nscherf** [comment]
So violin plots are OK here I think

**Comment by jkh1** [comment]
When comparing distributions I tend to prefer ridgeline plots or histograms. However, now that we're discussing this, I think there aren't enough data points here for this type of representation (including for violin plots) and would prefer showing the actual values (as jittered points to avoid overlap, which is what I know as a strip plot).

**Comment by haesleinhuepf** [comment]
The strip plot is shown above @jkh1 . It's super hard to see differences between models

**Comment by jkh1** [comment]
Right. There are a few issues with the strip plot above. The main one is that the points aren't jittered (or not enough) so that they overlap and make the locations of higher density invisible, another is maybe there are too few points spread over too many values. It may also be more readable/intuitive if rotated (i.e. values in y and models in x). My concern is that estimation of density may be inaccurate with too few points although violin plots are probably OK here to get a rough idea of the shape of the distribution but in light of having few points spread over many values, could be misleading (for example there is still a line where there are no data point). Maybe the differences this shows aren't that meaningful except for the extremes?
